---
title: "My english activity log"
---
# 2019

October 10, watching " shazam " and " the art of self-defense " in VO and english subtiltes 

october 14.15.16.17 watching the offical broadcast of the 2019 league of legends world championship  
[( Official league of legends broadcast )](https://www.twitch.tv/riotgames)

October 19, I watch 2 movies  " long shot " and " the nice guy " 

october 21 [(a video about how sex and mathematics are linked)](https://www.youtube.com/watch?v=H2vN2QXZGnc)

october 22 [(video about male suicide)](https://www.youtube.com/watch?v=Q3WDw-DBKLA) 

october 29  listening to a lot of pirate-like song 
[(pirate-like songs )](https://www.youtube.com/watch?v=EiV0PSfBics&list=PLw1XxchskYzzU6GcuPk12TNQ_wUjSQqdW) 
my favorite one [(Ye Banished Privateers - Ship is Sinking)](https://www.youtube.com/watch?v=ZBfvlyEgqZk&list=PLw1XxchskYzzU6GcuPk12TNQ_wUjSQqdW&index=10) 

october 30 [(Jordan peterson about lies )](https://www.youtube.com/watch?v=JjfClL6nogo) 

Novembre 03 [(Tedx Talks about bodybuilding )](https://www.youtube.com/watch?v=CR5krXHkr2I)

November 06 [(Funny videos from Anwar Jibawi )](https://www.youtube.com/watch?v=Mh_4EO_Qb5s)
            [(an anotger funny videos from Anwar Jibawi)](https://www.youtube.com/watch?v=g4BLENR3OFM&feature=youtu.be&fbclid=IwAR3OaTqx7tSSUWGi3KQFtXuU5KYe6StfaAiFVj2FUSAIH2Q1JGLlj6hEa2c)

November 14 [(videos about tatoos in korea )](https://www.youtube.com/watch?v=wHCo0Iwra0I) ( i don't like VICE at all the video wasn't very interesiting )
 [(documenting myself about cancer )](https://www.bordet.be/en/blood-cancer)
 
December 10 [(Jordan Peterson vs The Gender Pay Gap)](https://www.youtube.com/watch?v=Xg2psply4no) [(Jordan Peterson speaking about gender pronouns )](https://www.youtube.com/watch?v=Xg2psply4no) ( very interesting videos )
