---
title: "Creating versatile artificial muscles for life-like robots"
description: |
  Scientist find out how to make artificial muscles that looks even more like real muscles.
author:
  - name: SHENGQIANG CAI
    url: {}
date: 04-22-2020
preview: asd.png
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Advanced Sciences News

[Link : https://www.advancedsciencenews.com/creating-versatile-artificial-muscles-for-life-like-robots/](https://www.advancedsciencenews.com/creating-versatile-artificial-muscles-for-life-like-robots/)

## Vocabulary 

| Words from the text  | Synonym/explanation in English |
| -------------------- | ------------------------------ |
| Soft robots          | New generation of robot that are soft they act more like living things |
| Actuation            | Triggering |
| Versatility          | Adaptability |
| Completion           | The accomplishment of ...         |
| Embedded             | Integrated                    |
| Bond                 | link         |
| Carry out            | Achieve / do                   |
| wide                 | Opposite of narrow        |



## Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | SHENGQIANG CAI: : Assistant Professor, Mechanical and Aerospace Engineering, UC San Diego                       |
| Published in?                | 11 march 2020)                                                       |
| General topic?               |  They discovered artificial muscles that could have more than one shape thank's to liquid crystal that can change it's form when cooled.                       |
| Procedure/what was examined? | They created an " Elastomer " that is made of liquid crystal it was the main thing studied. |
| Conclusions/discovery?       |  They find out that this elastomer was working very well and could be adapt to soft robots and soft machines      |
| Remaining questions?         | How the crystal liquid can change in the robot and how the rearrangement work ? |

