---
title: "Pistons are muscling up"
description: |
  New generation of piston made of soft materials can work under lower pressure with more efficiency.
author:
  - name: Benjamin Boettner
    url: {}
date: 04-30-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Wyss Institute.

[Link : https://wyss.harvard.edu/news/pistons-are-muscling-up/](https://wyss.harvard.edu/news/pistons-are-muscling-up/)

## Vocabulary 

| Words from the text  | Synonym/explanation in English |
| -------------------- | ------------------------------ |
| Soft                 | opposite of hard  |
| plethora             | big variety of  |
| harness              | to exploit |
| chamber’s inner wall | the wall that is inside de chamber ...         |
| tight seal           | airtight / a seal that dosn't let water come in.                    |
| a shaft              | bar         |
| shortcomings         | deficiency                   |
| empower              | gain in power          | 
| folded               | bend / curl |
| embedded             | integrated / installed |
| within               | that is in something.         |
| sealed               | closed                    |
| triggers             | cause / generate / set off         |
| shape-shift          | something that take the shape of an another thing.                   |
| grasp                | hold / grip         |
| surrounding          | arround |
| task                 | mission / assignement |
| hinged               | articulate         |
| tunable              | that can be modified                    |


## Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | Wyss Institute and SEAS researchers Daniel Vogt, a Research Engineer at the Wyss Institute and Nicholas Bartlett       |
| Published in?                | 06 juin 2019)                                                       |
| General topic?               | They created a new kind of piston that use artificial muscles to work                |
| Procedure/what was examined? | They made a lot of test under low pressure and their ' piston tension ' is as efficient as usual one. Because they use FOAM material ( which is mainly material that looks like origami ) so when you lower the pressure the artificial muscles kinda shrivel up and lift something at the same time. |
| Conclusions/discovery?       | They made a test that compare tension piston and regular piston at crushing objects. The piston tension was as good as the regular one but was working under lower pressure.      |
| Remaining questions?         | None |

