---
title: "Artificial “muscles” achieve powerful pulling force"
description: |
  Artificial fiber that contratcs could mimic real muscles. Those reaserch could be a very good thing for biomedical devices and robotics
author:
  - name: David L. Chandler
    url: {}
date: 02-10-2019
preview: test.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# MIT NEWS

[Link : http://news.mit.edu/2019/artificial-fiber-muscles-0711](http://news.mit.edu/2019/artificial-fiber-muscles-0711)

## Vocabulary 

| Words from the text  | Synonym/explanation in English |
| -------------------- | ------------------------------ |
| sprouts              | germinate |
| coiled               | wound / wrap |
| limbs                | part of the body                   |
| strand               | fiber                  |
| mating               | join / match         |
| rates                | frequency        |
| heated               | warmed         |
| strip                | line         |
| held back            | retained         |
| bonded               | linked        |
| curls up             | cower / cringe / crouch         |
| stretchable          | that can be streched        |
| stiffer              | more rigid / more tight         |
| tight                | rigid / stiff / steep         |
| tendrils             | tentacles         |
| serendipity          | Something that wasn't supposed to happend but that's a good thing that it happend          |
| warmth               | enthusiasm         |
| pulling              | the opposite of pushing         |
| span                 | interval         |
| batches              | array         |
| lifting              | pulling / carrying         |
| loads                | bundle         |
| tuned                | modulate / accommodate         |
| trigger              | set off         |
| oversized            | too big         |
| viscous              | thick liquid          |
| purposes             | goal          |
| coated               | covered         |
| nanowires            | tiny wires ( 10^-9m)        |
| sensors              | detector         |
| actuators            | the things that trigger |
|tiny| very little         |
|bundled| loads, packed         |
|feedback| information that has been given back         |
|closed-loop| a circle        |
|limitless| with no limits         |
|realm| universe / free land          |

## Analysis table 

| Words from the text          | Synonym/explanation in English |
| ---------------------------- | ------------------------------ |
| Researchers                  | David L. Chandler                        |
| Published in?                | July 11, 2019                                                        |
| General topic?               | Artificial muscles that may help robotics and biomedical devices.                      |
| Procedure/what was examined? | No actual methodology explained, they tried to recreate the coiling-and-pulling mechanism that the cucumber plant does |
| Conclusions/discovery?       | They were able to create microscopic fiber tha could lif way mother than their own weight very easily just by warming them  |
| Remaining questions?         | None |
